USE [master]
GO
/****** Object:  Database [VehicleDB]    Script Date: 05/07/2012 22:26:32 ******/
CREATE DATABASE [VehicleDB] ON  PRIMARY 
( NAME = N'VehicleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\VehicleDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'VehicleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\VehicleDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [VehicleDB] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VehicleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VehicleDB] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [VehicleDB] SET ANSI_NULLS OFF
GO
ALTER DATABASE [VehicleDB] SET ANSI_PADDING OFF
GO
ALTER DATABASE [VehicleDB] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [VehicleDB] SET ARITHABORT OFF
GO
ALTER DATABASE [VehicleDB] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [VehicleDB] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [VehicleDB] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [VehicleDB] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [VehicleDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [VehicleDB] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [VehicleDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [VehicleDB] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [VehicleDB] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [VehicleDB] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [VehicleDB] SET  DISABLE_BROKER
GO
ALTER DATABASE [VehicleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [VehicleDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [VehicleDB] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [VehicleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [VehicleDB] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [VehicleDB] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [VehicleDB] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [VehicleDB] SET  READ_WRITE
GO
ALTER DATABASE [VehicleDB] SET RECOVERY FULL
GO
ALTER DATABASE [VehicleDB] SET  MULTI_USER
GO
ALTER DATABASE [VehicleDB] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [VehicleDB] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'VehicleDB', N'ON'
GO
USE [VehicleDB]
GO
/****** Object:  Table [dbo].[Vehicles]    Script Date: 05/07/2012 22:26:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Vehicles](
	[Id] [int] NOT NULL,
	[Type] [varchar](50) NOT NULL,
	[Vin] [char](10) NOT NULL,
	[Make] [varchar](50) NOT NULL,
	[Model] [varchar](50) NOT NULL,
	[Year] [int] NOT NULL,
	[TireSize] [varchar](50) NULL,
	[PropSize] [varchar](50) NULL,
 CONSTRAINT [PK_Vehicles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
